version = 0.1

### Dev環境 ###
[dev]
# build
[dev.build]
[dev.build.parameters]
# deploy
[dev.deploy]
[dev.deploy.parameters]
region = "ap-northeast-3"
parameter_overrides = "Env=dev"
confirm_changeset = true
capabilities = [CAPABILITY_IAM]
disable_rollback = true
image_repositories = []

### Prod環境 ###
[prod]
# build
[prod.build.parameters]
# deploy
[prod.deploy]
[prod.deploy.parameters]
region = "ap-northeast-3"
parameter_overrides = "Env=prod"
confirm_changeset = true
capabilities = [CAPABILITY_IAM]
disable_rollback = true
image_repositories = []