
name: Operation user pool (develop)

on:
  push:
    branches:
      - develop   # 開発環境
    paths:
    - resources/cognito_operation_users/**
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
  
jobs:
  ####### Deploy(CD) #######
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: SAM Build
        run: sam build --template-file cognit_operation_users.yml
        working-directory: resources/cognito_operation_users

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file cognit_operation_users.yml \
            --config-file cognit_operation_users.toml \
            --config-env dev \
            --stack-name dev-${{ secrets.APP_NAME }}-cognito-operation-users \
            --parameter-overrides \
              AppName=${{ secrets.APP_NAME }} \
              DomainName=${{ secrets.DOMAIN_NAME_DEV }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: resources/cognito_operation_users