
name: Lambda Functions for Operations Site (develop)

on:
  push:
    branches:
      - develop   # 開発環境
    paths:
    - backend/commons/auth_manager/**
    - backend/commons/logger/**
    - backend/operations/**
    - resources/lambda/lambda_operations.yml
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
  
jobs:
  ####### Deploy(CD) #######
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.22.0

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: backend/pnpm-lock.yaml

      - name: Install esbuild globally
        run: npm install -g esbuild@0.25.12


      ### Lambda Aurhorizer & Operations Build ###
      - name: Install Lambda Operations Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: backend
        
      - name: Lambda Operations Build(common)
        run: |
          pnpm --filter @commons/auth_manager tsc
          pnpm --filter @commons/auth_manager build
          pnpm --filter @commons/logger tsc
          pnpm --filter @commons/logger build
        working-directory: backend

      - name: Lambda Authorizer Build(authorizer)
        run: pnpm --filter @authorizer/operations build
        working-directory: backend

      #- name: Lambda Operations Build(operations)
      #  run: pnpm --filter @operations/* build
      #  working-directory: backend


      ### AWS Credentials ###
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}


      ### SAM Deploy ###
      - name: SAM Build
        run: sam build --template-file lambda_operations.yml
        working-directory: resources/lambda

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file lambda_operations.yml \
            --stack-name lambda-operations \
            --resolve-s3 \
            --parameter-overrides \
              Env=dev \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: resources/lambda
