
name: Static contents distribution using S3 and CloudFront with AWS SAM (Dev/Prod switch)

on:
  push:
    branches:
      - develop   # 開発環境
      - main
  workflow_dispatch:
    
# allow use id-token
permissions:
  id-token: write # required!
  contents: read
  
jobs:
  ####### Build(CI) #######
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#      
#      - name: Use Node.js 22.x
#        uses: actions/setup-node@v4
#        with:
#          node-version: 22
#  
#      - name: Install Dependencies
#        run: npm install
#        working-directory: frontend/admin
#
#      - name: Frontend Build
#        run: npm run build
#        working-directory: frontend/admin

  ####### Deploy(CD) #######
  deploy:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: SAM Build
        run: sam build --template-file userinterface_admin.yaml
        working-directory: ./resources/userinterface_admin

      - name: SAM Deploy
        run: sam deploy \
            --template-file userinterface_admin.yaml \
            --stack-name ${{ secrets.STACK_NAME_DEV }} \
            --AppName ${{ secrets.APP_NAME_DEV }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: ./resources/userinterface_admin

