
name: Admin site distribution using S3 and CloudFront with AWS SAM (develop)

on:
  push:
    branches:
      - develop   # 開発環境
    paths:
    - frontend/admin/**
    - resources/userinterface_admin/**
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
  
jobs:
  ####### Build(CI) #######
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
  
      - name: Install Dependencies
        run: npm install
        working-directory: frontend/admin

      - name: Frontend Build
        run: npm run build
        working-directory: frontend/admin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-admin-build
          path: frontend/admin/dist

  ####### Deploy(CD) #######
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-admin-build
          path: dist
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: SAM Build
        run: sam build --template-file userinterface_admin.yml
        working-directory: resources/userinterface_admin

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file userinterface_admin.yml \
            --config-file userinterface_admin.toml \
            --config-env dev \
            --stack-name dev-${{ secrets.APP_NAME }}-userinterface-admin \
            --parameter-overrides AppName=${{ secrets.APP_NAME }} \
            --parameter-overrides DomainName=${{ secrets.DOMAIN_NAME_DEV }} \
            --parameter-overrides HostedZoneId=${{ secrets.HOSTED_ZONE_ID }} \
            --parameter-overrides CertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: resources/userinterface_admin

      #- name: Upload to S3
      #  run: aws s3 sync dist s3://dev-${{ secrets.APP_NAME }}-admin-site-bucket --delete  
