
name: Operations site distribution (develop)

on:
  push:
    branches:
      - develop   # 開発環境
    paths:
    - frontend/operations/**
    - backend/commons/auth_manager/**
    - backend/commons/logger/**
    - backend/authorizer/operation/**
    - resources/userinterface/userinterface_operations.yml
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
  
jobs:
  ####### Build(CI) #######
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.22.0
      
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: backend/pnpm-lock.yaml
  
      - name: Install Dependencies
        run: npm install --frozen-lockfile
        working-directory: frontend/operations
      - name: Frontend Build
        run: npm run build
        working-directory: frontend/operations
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-operations-build
          path: frontend/operations/dist

      - name: Install Lambda Authorizer Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: backend
      - name: Lambda Authorizer Build(common)
        run: |
          pnpm --filter @commons/auth_manager tsc
          pnpm --filter @commons/auth_manager build
          pnpm --filter @commons/logger tsc
          pnpm --filter @commons/logger build
        working-directory: backend
      - name: Lambda Authorizer Build(authorizer)
        run: pnpm --filter @authorizer/operation build
        working-directory: backend
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-operations-build
          path: backend/authorizer/operation/dist

  ####### Deploy(CD) #######
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact Frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-operations-build
          path: dist
      - name: Download Build Artifact Backend
        uses: actions/download-artifact@v4
        with:
          name: backend-operations-build
          path: backend/authorizer/operation/dist
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: SAM Build
        run: sam build --template-file userinterface_operations.yml
        working-directory: resources/userinterface

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file userinterface_operations.yml \
            --config-file userinterface_operations.toml \
            --config-env dev \
            --stack-name userinterface-operations \
            --resolve-s3 \
            --parameter-overrides \
              Env=dev \
              AppName=${{ secrets.APP_NAME }} \
              DomainName=${{ secrets.DOMAIN_NAME_DEV }} \
              HostedZoneId=${{ secrets.HOSTED_ZONE_ID }} \
              CertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: resources/userinterface

      #- name: Upload to S3
      #  run: aws s3 sync dist s3://dev-${{ secrets.APP_NAME }}-operations-site-bucket --delete  